{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create a Linkedin app to get your Linkedin credentials\n",
    "## Please check the documentaion for more details.\n",
    "TIKTOK_KEY='awvdj7d878ehk0zl'\n",
    "TIKTOK_SECRET='faa31e6ea3cef7dfc0888110168754d1'\n",
    "\n",
    "# Create a TIKTOK app to get your Linkedin credentials\n",
    "TIKTOK_ACCESS_TOKEN_KEY='awykvnk5xvj06qxl'\n",
    "TIKTOK_ACCESS_TOKEN_SECRET='9a6880fc55b7a3099638401423084da6'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "ename": "RuntimeError",
     "evalue": "This event loop is already running",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mRuntimeError\u001b[0m                              Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[14], line 14\u001b[0m\n\u001b[0;32m     12\u001b[0m verifyFp \u001b[39m=\u001b[39m \u001b[39m\"\u001b[39m\u001b[39mverify_le9rb5f3_SKVVDvZX_FXMx_4Wjy_8Gcm_XnP8yEnwhQ1c\u001b[39m\u001b[39m\"\u001b[39m\n\u001b[0;32m     13\u001b[0m \u001b[39m# Setup instance\u001b[39;00m\n\u001b[1;32m---> 14\u001b[0m api \u001b[39m=\u001b[39m tiktok(custom_verifyFp\u001b[39m=\u001b[39;49mverifyFp)\n\u001b[0;32m     15\u001b[0m \u001b[39m# Get data by hashtag\u001b[39;00m\n\u001b[0;32m     16\u001b[0m \u001b[39m# trending = api.by_hashtag(hashtag)\u001b[39;00m\n\u001b[0;32m     17\u001b[0m \u001b[39m# # Process data\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m     20\u001b[0m \u001b[39m# df = pd.DataFrame.from_dict(flattened_data, orient='index')\u001b[39;00m\n\u001b[0;32m     21\u001b[0m \u001b[39m# df.to_csv('tiktokdata.csv', index=False)\u001b[39;00m\n",
      "File \u001b[1;32md:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\TikTokApi\\tiktok.py:159\u001b[0m, in \u001b[0;36mTikTokApi.__init__\u001b[1;34m(self, logging_level, request_delay, custom_device_id, generate_static_device_id, custom_verify_fp, use_test_endpoints, proxy, executable_path, *args, **kwargs)\u001b[0m\n\u001b[0;32m    156\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mlogger\u001b[39m.\u001b[39msetLevel(logging_level)\n\u001b[0;32m    158\u001b[0m \u001b[39mwith\u001b[39;00m _thread_lock:\n\u001b[1;32m--> 159\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_initialize(\n\u001b[0;32m    160\u001b[0m         request_delay\u001b[39m=\u001b[39mrequest_delay,\n\u001b[0;32m    161\u001b[0m         custom_device_id\u001b[39m=\u001b[39mcustom_device_id,\n\u001b[0;32m    162\u001b[0m         generate_static_device_id\u001b[39m=\u001b[39mgenerate_static_device_id,\n\u001b[0;32m    163\u001b[0m         custom_verify_fp\u001b[39m=\u001b[39mcustom_verify_fp,\n\u001b[0;32m    164\u001b[0m         use_test_endpoints\u001b[39m=\u001b[39muse_test_endpoints,\n\u001b[0;32m    165\u001b[0m         proxy\u001b[39m=\u001b[39mproxy,\n\u001b[0;32m    166\u001b[0m         executable_path\u001b[39m=\u001b[39mexecutable_path,\n\u001b[0;32m    167\u001b[0m         \u001b[39m*\u001b[39margs,\n\u001b[0;32m    168\u001b[0m         \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs,\n\u001b[0;32m    169\u001b[0m     )\n",
      "File \u001b[1;32md:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\TikTokApi\\tiktok.py:205\u001b[0m, in \u001b[0;36mTikTokApi._initialize\u001b[1;34m(self, **kwargs)\u001b[0m\n\u001b[0;32m    200\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_custom_device_id \u001b[39m=\u001b[39m \u001b[39m\"\u001b[39m\u001b[39m\"\u001b[39m\u001b[39m.\u001b[39mjoin(\n\u001b[0;32m    201\u001b[0m         random\u001b[39m.\u001b[39mchoice(string\u001b[39m.\u001b[39mdigits) \u001b[39mfor\u001b[39;00m num \u001b[39min\u001b[39;00m \u001b[39mrange\u001b[39m(\u001b[39m19\u001b[39m)\n\u001b[0;32m    202\u001b[0m     )\n\u001b[0;32m    204\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_signer_url \u001b[39mis\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[1;32m--> 205\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_browser \u001b[39m=\u001b[39m asyncio\u001b[39m.\u001b[39;49mget_event_loop()\u001b[39m.\u001b[39;49mrun_until_complete(\n\u001b[0;32m    206\u001b[0m         asyncio\u001b[39m.\u001b[39;49mgather(browser\u001b[39m.\u001b[39;49mcreate(\u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs))\n\u001b[0;32m    207\u001b[0m     )[\u001b[39m0\u001b[39m]\n\u001b[0;32m    209\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_user_agent \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_browser\u001b[39m.\u001b[39muser_agent\n\u001b[0;32m    211\u001b[0m \u001b[39mtry\u001b[39;00m:\n",
      "File \u001b[1;32mC:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\base_events.py:625\u001b[0m, in \u001b[0;36mBaseEventLoop.run_until_complete\u001b[1;34m(self, future)\u001b[0m\n\u001b[0;32m    614\u001b[0m \u001b[39m\u001b[39m\u001b[39m\"\"\"Run until the Future is done.\u001b[39;00m\n\u001b[0;32m    615\u001b[0m \n\u001b[0;32m    616\u001b[0m \u001b[39mIf the argument is a coroutine, it is wrapped in a Task.\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    622\u001b[0m \u001b[39mReturn the Future's result, or raise its exception.\u001b[39;00m\n\u001b[0;32m    623\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[0;32m    624\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_check_closed()\n\u001b[1;32m--> 625\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_check_running()\n\u001b[0;32m    627\u001b[0m new_task \u001b[39m=\u001b[39m \u001b[39mnot\u001b[39;00m futures\u001b[39m.\u001b[39misfuture(future)\n\u001b[0;32m    628\u001b[0m future \u001b[39m=\u001b[39m tasks\u001b[39m.\u001b[39mensure_future(future, loop\u001b[39m=\u001b[39m\u001b[39mself\u001b[39m)\n",
      "File \u001b[1;32mC:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\base_events.py:584\u001b[0m, in \u001b[0;36mBaseEventLoop._check_running\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    582\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_check_running\u001b[39m(\u001b[39mself\u001b[39m):\n\u001b[0;32m    583\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mis_running():\n\u001b[1;32m--> 584\u001b[0m         \u001b[39mraise\u001b[39;00m \u001b[39mRuntimeError\u001b[39;00m(\u001b[39m'\u001b[39m\u001b[39mThis event loop is already running\u001b[39m\u001b[39m'\u001b[39m)\n\u001b[0;32m    585\u001b[0m     \u001b[39mif\u001b[39;00m events\u001b[39m.\u001b[39m_get_running_loop() \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[0;32m    586\u001b[0m         \u001b[39mraise\u001b[39;00m \u001b[39mRuntimeError\u001b[39;00m(\n\u001b[0;32m    587\u001b[0m             \u001b[39m'\u001b[39m\u001b[39mCannot run the event loop while another loop is running\u001b[39m\u001b[39m'\u001b[39m)\n",
      "\u001b[1;31mRuntimeError\u001b[0m: This event loop is already running"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-17' coro=<Connection.run() done, defined at d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\playwright\\_impl\\_connection.py:240> exception=NotImplementedError()>\n",
      "Traceback (most recent call last):\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\playwright\\_impl\\_connection.py\", line 247, in run\n",
      "    await self._transport.connect()\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\playwright\\_impl\\_transport.py\", line 127, in connect\n",
      "    raise exc\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\playwright\\_impl\\_transport.py\", line 116, in connect\n",
      "    self._proc = await asyncio.create_subprocess_exec(\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\subprocess.py\", line 218, in create_subprocess_exec\n",
      "    transport, protocol = await loop.subprocess_exec(\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\base_events.py\", line 1681, in subprocess_exec\n",
      "    transport = await self._make_subprocess_transport(\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\base_events.py\", line 498, in _make_subprocess_transport\n",
      "    raise NotImplementedError\n",
      "NotImplementedError\n"
     ]
    }
   ],
   "source": [
    "# voir  test .py\n",
    "# Importing the tiktok Python SDK\n",
    "from TikTokApi import TikTokApi as tiktok\n",
    "# Import JSON for export of data\n",
    "import json\n",
    "# Import data processing helper\n",
    "# from helpers import process_results \n",
    "# Import pandas to create dataframes\n",
    "import pandas as pd\n",
    "# Import sys dependency to extract command line arguments\n",
    "import sys\n",
    "# Get cookie data\n",
    "verifyFp = \"verify_le9rb5f3_SKVVDvZX_FXMx_4Wjy_8Gcm_XnP8yEnwhQ1c\"\n",
    "# Setup instance\n",
    "api = tiktok(custom_verifyFp=verifyFp)\n",
    "# Get data by hashtag\n",
    "# trending = api.by_hashtag(hashtag)\n",
    "# # Process data\n",
    "# flattened_data = process_results(trending)\n",
    "# # Convert the preprocessed data to a dataframe\n",
    "# df = pd.DataFrame.from_dict(flattened_data, orient='index')\n",
    "# df.to_csv('tiktokdata.csv', index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function TikTokApi.__del__ at 0x000002067C6D8280>\n",
      "Traceback (most recent call last):\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\TikTokApi\\tiktok.py\", line 421, in __del__\n",
      "    self.shutdown()\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\TikTokApi\\tiktok.py\", line 635, in shutdown\n",
      "    asyncio.get_event_loop().run_until_complete(self._browser._clean_up())\n",
      "AttributeError: 'TikTokApi' object has no attribute '_browser'\n",
      "_GatheringFuture exception was never retrieved\n",
      "future: <_GatheringFuture finished exception=NotImplementedError()>\n",
      "Traceback (most recent call last):\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\TikTokApi\\browser_utilities\\browser.py\", line 74, in create\n",
      "    self._thread_locals.playwright = await async_playwright().start()\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\playwright\\async_api\\_context_manager.py\", line 51, in start\n",
      "    return await self.__aenter__()\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\playwright\\async_api\\_context_manager.py\", line 46, in __aenter__\n",
      "    playwright = AsyncPlaywright(next(iter(done)).result())\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\playwright\\_impl\\_transport.py\", line 116, in connect\n",
      "    self._proc = await asyncio.create_subprocess_exec(\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\subprocess.py\", line 218, in create_subprocess_exec\n",
      "    transport, protocol = await loop.subprocess_exec(\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\base_events.py\", line 1681, in subprocess_exec\n",
      "    transport = await self._make_subprocess_transport(\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\base_events.py\", line 498, in _make_subprocess_transport\n",
      "    raise NotImplementedError\n",
      "NotImplementedError\n",
      "Exception ignored in: <function TikTokApi.__del__ at 0x000002067C6D8280>\n",
      "Traceback (most recent call last):\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\TikTokApi\\tiktok.py\", line 421, in __del__\n",
      "    self.shutdown()\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\TikTokApi\\tiktok.py\", line 635, in shutdown\n",
      "    asyncio.get_event_loop().run_until_complete(self._browser._clean_up())\n",
      "AttributeError: 'TikTokApi' object has no attribute '_browser'\n",
      "_GatheringFuture exception was never retrieved\n",
      "future: <_GatheringFuture finished exception=NotImplementedError()>\n",
      "Traceback (most recent call last):\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\TikTokApi\\browser_utilities\\browser.py\", line 74, in create\n",
      "    self._thread_locals.playwright = await async_playwright().start()\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\playwright\\async_api\\_context_manager.py\", line 51, in start\n",
      "    return await self.__aenter__()\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\playwright\\async_api\\_context_manager.py\", line 46, in __aenter__\n",
      "    playwright = AsyncPlaywright(next(iter(done)).result())\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\playwright\\_impl\\_transport.py\", line 116, in connect\n",
      "    self._proc = await asyncio.create_subprocess_exec(\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\subprocess.py\", line 218, in create_subprocess_exec\n",
      "    transport, protocol = await loop.subprocess_exec(\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\base_events.py\", line 1681, in subprocess_exec\n",
      "    transport = await self._make_subprocess_transport(\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\base_events.py\", line 498, in _make_subprocess_transport\n",
      "    raise NotImplementedError\n",
      "NotImplementedError\n",
      "Exception ignored in: <function TikTokApi.__del__ at 0x000002067C6D8280>\n",
      "Traceback (most recent call last):\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\TikTokApi\\tiktok.py\", line 421, in __del__\n",
      "    self.shutdown()\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\TikTokApi\\tiktok.py\", line 635, in shutdown\n",
      "    asyncio.get_event_loop().run_until_complete(self._browser._clean_up())\n",
      "AttributeError: 'TikTokApi' object has no attribute '_browser'\n",
      "_GatheringFuture exception was never retrieved\n",
      "future: <_GatheringFuture finished exception=NotImplementedError()>\n",
      "Traceback (most recent call last):\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\TikTokApi\\browser_utilities\\browser.py\", line 74, in create\n",
      "    self._thread_locals.playwright = await async_playwright().start()\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\playwright\\async_api\\_context_manager.py\", line 51, in start\n",
      "    return await self.__aenter__()\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\playwright\\async_api\\_context_manager.py\", line 46, in __aenter__\n",
      "    playwright = AsyncPlaywright(next(iter(done)).result())\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\playwright\\_impl\\_transport.py\", line 116, in connect\n",
      "    self._proc = await asyncio.create_subprocess_exec(\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\subprocess.py\", line 218, in create_subprocess_exec\n",
      "    transport, protocol = await loop.subprocess_exec(\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\base_events.py\", line 1681, in subprocess_exec\n",
      "    transport = await self._make_subprocess_transport(\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\base_events.py\", line 498, in _make_subprocess_transport\n",
      "    raise NotImplementedError\n",
      "NotImplementedError\n",
      "Exception ignored in: <function TikTokApi.__del__ at 0x000002067C6D8280>\n",
      "Traceback (most recent call last):\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\TikTokApi\\tiktok.py\", line 421, in __del__\n",
      "    self.shutdown()\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\TikTokApi\\tiktok.py\", line 635, in shutdown\n",
      "    asyncio.get_event_loop().run_until_complete(self._browser._clean_up())\n",
      "AttributeError: 'TikTokApi' object has no attribute '_browser'\n",
      "_GatheringFuture exception was never retrieved\n",
      "future: <_GatheringFuture finished exception=NotImplementedError()>\n",
      "Traceback (most recent call last):\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\TikTokApi\\browser_utilities\\browser.py\", line 74, in create\n",
      "    self._thread_locals.playwright = await async_playwright().start()\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\playwright\\async_api\\_context_manager.py\", line 51, in start\n",
      "    return await self.__aenter__()\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\playwright\\async_api\\_context_manager.py\", line 46, in __aenter__\n",
      "    playwright = AsyncPlaywright(next(iter(done)).result())\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\playwright\\_impl\\_transport.py\", line 116, in connect\n",
      "    self._proc = await asyncio.create_subprocess_exec(\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\subprocess.py\", line 218, in create_subprocess_exec\n",
      "    transport, protocol = await loop.subprocess_exec(\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\base_events.py\", line 1681, in subprocess_exec\n",
      "    transport = await self._make_subprocess_transport(\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\base_events.py\", line 498, in _make_subprocess_transport\n",
      "    raise NotImplementedError\n",
      "NotImplementedError\n",
      "Exception ignored in: <function TikTokApi.__del__ at 0x000002067C6D8280>\n",
      "Traceback (most recent call last):\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\TikTokApi\\tiktok.py\", line 421, in __del__\n",
      "    self.shutdown()\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\TikTokApi\\tiktok.py\", line 635, in shutdown\n",
      "    asyncio.get_event_loop().run_until_complete(self._browser._clean_up())\n",
      "AttributeError: 'TikTokApi' object has no attribute '_browser'\n",
      "_GatheringFuture exception was never retrieved\n",
      "future: <_GatheringFuture finished exception=NotImplementedError()>\n",
      "Traceback (most recent call last):\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\TikTokApi\\browser_utilities\\browser.py\", line 74, in create\n",
      "    self._thread_locals.playwright = await async_playwright().start()\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\playwright\\async_api\\_context_manager.py\", line 51, in start\n",
      "    return await self.__aenter__()\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\playwright\\async_api\\_context_manager.py\", line 46, in __aenter__\n",
      "    playwright = AsyncPlaywright(next(iter(done)).result())\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\playwright\\_impl\\_transport.py\", line 116, in connect\n",
      "    self._proc = await asyncio.create_subprocess_exec(\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\subprocess.py\", line 218, in create_subprocess_exec\n",
      "    transport, protocol = await loop.subprocess_exec(\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\base_events.py\", line 1681, in subprocess_exec\n",
      "    transport = await self._make_subprocess_transport(\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\base_events.py\", line 498, in _make_subprocess_transport\n",
      "    raise NotImplementedError\n",
      "NotImplementedError\n",
      "Exception ignored in: <function TikTokApi.__del__ at 0x000002067C6D8280>\n",
      "Traceback (most recent call last):\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\TikTokApi\\tiktok.py\", line 421, in __del__\n",
      "    self.shutdown()\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\TikTokApi\\tiktok.py\", line 635, in shutdown\n",
      "    asyncio.get_event_loop().run_until_complete(self._browser._clean_up())\n",
      "AttributeError: 'TikTokApi' object has no attribute '_browser'\n",
      "_GatheringFuture exception was never retrieved\n",
      "future: <_GatheringFuture finished exception=NotImplementedError()>\n",
      "Traceback (most recent call last):\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\TikTokApi\\browser_utilities\\browser.py\", line 74, in create\n",
      "    self._thread_locals.playwright = await async_playwright().start()\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\playwright\\async_api\\_context_manager.py\", line 51, in start\n",
      "    return await self.__aenter__()\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\playwright\\async_api\\_context_manager.py\", line 46, in __aenter__\n",
      "    playwright = AsyncPlaywright(next(iter(done)).result())\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\playwright\\_impl\\_transport.py\", line 116, in connect\n",
      "    self._proc = await asyncio.create_subprocess_exec(\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\subprocess.py\", line 218, in create_subprocess_exec\n",
      "    transport, protocol = await loop.subprocess_exec(\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\base_events.py\", line 1681, in subprocess_exec\n",
      "    transport = await self._make_subprocess_transport(\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\base_events.py\", line 498, in _make_subprocess_transport\n",
      "    raise NotImplementedError\n",
      "NotImplementedError\n"
     ]
    },
    {
     "ename": "RuntimeError",
     "evalue": "This event loop is already running",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mRuntimeError\u001b[0m                              Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[15], line 3\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mTikTokApi\u001b[39;00m \u001b[39mimport\u001b[39;00m TikTokApi\n\u001b[1;32m----> 3\u001b[0m \u001b[39mwith\u001b[39;00m TikTokApi() \u001b[39mas\u001b[39;00m api:\n\u001b[0;32m      4\u001b[0m     user \u001b[39m=\u001b[39m api\u001b[39m.\u001b[39muser(username\u001b[39m=\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mtherock\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[0;32m      6\u001b[0m     \u001b[39mfor\u001b[39;00m video \u001b[39min\u001b[39;00m user\u001b[39m.\u001b[39mvideos():\n",
      "File \u001b[1;32md:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\TikTokApi\\tiktok.py:159\u001b[0m, in \u001b[0;36mTikTokApi.__init__\u001b[1;34m(self, logging_level, request_delay, custom_device_id, generate_static_device_id, custom_verify_fp, use_test_endpoints, proxy, executable_path, *args, **kwargs)\u001b[0m\n\u001b[0;32m    156\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mlogger\u001b[39m.\u001b[39msetLevel(logging_level)\n\u001b[0;32m    158\u001b[0m \u001b[39mwith\u001b[39;00m _thread_lock:\n\u001b[1;32m--> 159\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_initialize(\n\u001b[0;32m    160\u001b[0m         request_delay\u001b[39m=\u001b[39mrequest_delay,\n\u001b[0;32m    161\u001b[0m         custom_device_id\u001b[39m=\u001b[39mcustom_device_id,\n\u001b[0;32m    162\u001b[0m         generate_static_device_id\u001b[39m=\u001b[39mgenerate_static_device_id,\n\u001b[0;32m    163\u001b[0m         custom_verify_fp\u001b[39m=\u001b[39mcustom_verify_fp,\n\u001b[0;32m    164\u001b[0m         use_test_endpoints\u001b[39m=\u001b[39muse_test_endpoints,\n\u001b[0;32m    165\u001b[0m         proxy\u001b[39m=\u001b[39mproxy,\n\u001b[0;32m    166\u001b[0m         executable_path\u001b[39m=\u001b[39mexecutable_path,\n\u001b[0;32m    167\u001b[0m         \u001b[39m*\u001b[39margs,\n\u001b[0;32m    168\u001b[0m         \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs,\n\u001b[0;32m    169\u001b[0m     )\n",
      "File \u001b[1;32md:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\TikTokApi\\tiktok.py:205\u001b[0m, in \u001b[0;36mTikTokApi._initialize\u001b[1;34m(self, **kwargs)\u001b[0m\n\u001b[0;32m    200\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_custom_device_id \u001b[39m=\u001b[39m \u001b[39m\"\u001b[39m\u001b[39m\"\u001b[39m\u001b[39m.\u001b[39mjoin(\n\u001b[0;32m    201\u001b[0m         random\u001b[39m.\u001b[39mchoice(string\u001b[39m.\u001b[39mdigits) \u001b[39mfor\u001b[39;00m num \u001b[39min\u001b[39;00m \u001b[39mrange\u001b[39m(\u001b[39m19\u001b[39m)\n\u001b[0;32m    202\u001b[0m     )\n\u001b[0;32m    204\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_signer_url \u001b[39mis\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[1;32m--> 205\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_browser \u001b[39m=\u001b[39m asyncio\u001b[39m.\u001b[39;49mget_event_loop()\u001b[39m.\u001b[39;49mrun_until_complete(\n\u001b[0;32m    206\u001b[0m         asyncio\u001b[39m.\u001b[39;49mgather(browser\u001b[39m.\u001b[39;49mcreate(\u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs))\n\u001b[0;32m    207\u001b[0m     )[\u001b[39m0\u001b[39m]\n\u001b[0;32m    209\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_user_agent \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_browser\u001b[39m.\u001b[39muser_agent\n\u001b[0;32m    211\u001b[0m \u001b[39mtry\u001b[39;00m:\n",
      "File \u001b[1;32mC:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\base_events.py:625\u001b[0m, in \u001b[0;36mBaseEventLoop.run_until_complete\u001b[1;34m(self, future)\u001b[0m\n\u001b[0;32m    614\u001b[0m \u001b[39m\u001b[39m\u001b[39m\"\"\"Run until the Future is done.\u001b[39;00m\n\u001b[0;32m    615\u001b[0m \n\u001b[0;32m    616\u001b[0m \u001b[39mIf the argument is a coroutine, it is wrapped in a Task.\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    622\u001b[0m \u001b[39mReturn the Future's result, or raise its exception.\u001b[39;00m\n\u001b[0;32m    623\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[0;32m    624\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_check_closed()\n\u001b[1;32m--> 625\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_check_running()\n\u001b[0;32m    627\u001b[0m new_task \u001b[39m=\u001b[39m \u001b[39mnot\u001b[39;00m futures\u001b[39m.\u001b[39misfuture(future)\n\u001b[0;32m    628\u001b[0m future \u001b[39m=\u001b[39m tasks\u001b[39m.\u001b[39mensure_future(future, loop\u001b[39m=\u001b[39m\u001b[39mself\u001b[39m)\n",
      "File \u001b[1;32mC:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\base_events.py:584\u001b[0m, in \u001b[0;36mBaseEventLoop._check_running\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    582\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_check_running\u001b[39m(\u001b[39mself\u001b[39m):\n\u001b[0;32m    583\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mis_running():\n\u001b[1;32m--> 584\u001b[0m         \u001b[39mraise\u001b[39;00m \u001b[39mRuntimeError\u001b[39;00m(\u001b[39m'\u001b[39m\u001b[39mThis event loop is already running\u001b[39m\u001b[39m'\u001b[39m)\n\u001b[0;32m    585\u001b[0m     \u001b[39mif\u001b[39;00m events\u001b[39m.\u001b[39m_get_running_loop() \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[0;32m    586\u001b[0m         \u001b[39mraise\u001b[39;00m \u001b[39mRuntimeError\u001b[39;00m(\n\u001b[0;32m    587\u001b[0m             \u001b[39m'\u001b[39m\u001b[39mCannot run the event loop while another loop is running\u001b[39m\u001b[39m'\u001b[39m)\n",
      "\u001b[1;31mRuntimeError\u001b[0m: This event loop is already running"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-19' coro=<Connection.run() done, defined at d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\playwright\\_impl\\_connection.py:240> exception=NotImplementedError()>\n",
      "Traceback (most recent call last):\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\playwright\\_impl\\_connection.py\", line 247, in run\n",
      "    await self._transport.connect()\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\playwright\\_impl\\_transport.py\", line 127, in connect\n",
      "    raise exc\n",
      "  File \"d:\\dsi\\PFE\\AI\\env\\lib\\site-packages\\playwright\\_impl\\_transport.py\", line 116, in connect\n",
      "    self._proc = await asyncio.create_subprocess_exec(\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\subprocess.py\", line 218, in create_subprocess_exec\n",
      "    transport, protocol = await loop.subprocess_exec(\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\base_events.py\", line 1681, in subprocess_exec\n",
      "    transport = await self._make_subprocess_transport(\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\asyncio\\base_events.py\", line 498, in _make_subprocess_transport\n",
      "    raise NotImplementedError\n",
      "NotImplementedError\n"
     ]
    }
   ],
   "source": [
    "\n",
    "from TikTokApi import TikTokApi\n",
    "\n",
    "with TikTokApi() as api:\n",
    "    user = api.user(username=\"therock\")\n",
    "\n",
    "    for video in user.videos():\n",
    "        print(video.id)\n",
    "\n",
    "    for liked_video in api.user(username=\"public_likes\").videos():\n",
    "        print(liked_video.id)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "ename": "RuntimeError",
     "evalue": "This event loop is already running",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mRuntimeError\u001b[0m                              Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[1], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mTikTokApi\u001b[39;00m \u001b[39mimport\u001b[39;00m TikTokApi\n\u001b[0;32m----> 2\u001b[0m api \u001b[39m=\u001b[39m TikTokApi()\n",
      "File \u001b[0;32m~/Documents/AI/env/lib/python3.8/site-packages/TikTokApi/tiktok.py:159\u001b[0m, in \u001b[0;36mTikTokApi.__init__\u001b[0;34m(self, logging_level, request_delay, custom_device_id, generate_static_device_id, custom_verify_fp, use_test_endpoints, proxy, executable_path, *args, **kwargs)\u001b[0m\n\u001b[1;32m    156\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mlogger\u001b[39m.\u001b[39msetLevel(logging_level)\n\u001b[1;32m    158\u001b[0m \u001b[39mwith\u001b[39;00m _thread_lock:\n\u001b[0;32m--> 159\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_initialize(\n\u001b[1;32m    160\u001b[0m         request_delay\u001b[39m=\u001b[39;49mrequest_delay,\n\u001b[1;32m    161\u001b[0m         custom_device_id\u001b[39m=\u001b[39;49mcustom_device_id,\n\u001b[1;32m    162\u001b[0m         generate_static_device_id\u001b[39m=\u001b[39;49mgenerate_static_device_id,\n\u001b[1;32m    163\u001b[0m         custom_verify_fp\u001b[39m=\u001b[39;49mcustom_verify_fp,\n\u001b[1;32m    164\u001b[0m         use_test_endpoints\u001b[39m=\u001b[39;49muse_test_endpoints,\n\u001b[1;32m    165\u001b[0m         proxy\u001b[39m=\u001b[39;49mproxy,\n\u001b[1;32m    166\u001b[0m         executable_path\u001b[39m=\u001b[39;49mexecutable_path,\n\u001b[1;32m    167\u001b[0m         \u001b[39m*\u001b[39;49margs,\n\u001b[1;32m    168\u001b[0m         \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs,\n\u001b[1;32m    169\u001b[0m     )\n",
      "File \u001b[0;32m~/Documents/AI/env/lib/python3.8/site-packages/TikTokApi/tiktok.py:205\u001b[0m, in \u001b[0;36mTikTokApi._initialize\u001b[0;34m(self, **kwargs)\u001b[0m\n\u001b[1;32m    200\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_custom_device_id \u001b[39m=\u001b[39m \u001b[39m\"\u001b[39m\u001b[39m\"\u001b[39m\u001b[39m.\u001b[39mjoin(\n\u001b[1;32m    201\u001b[0m         random\u001b[39m.\u001b[39mchoice(string\u001b[39m.\u001b[39mdigits) \u001b[39mfor\u001b[39;00m num \u001b[39min\u001b[39;00m \u001b[39mrange\u001b[39m(\u001b[39m19\u001b[39m)\n\u001b[1;32m    202\u001b[0m     )\n\u001b[1;32m    204\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_signer_url \u001b[39mis\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[0;32m--> 205\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_browser \u001b[39m=\u001b[39m asyncio\u001b[39m.\u001b[39;49mget_event_loop()\u001b[39m.\u001b[39;49mrun_until_complete(\n\u001b[1;32m    206\u001b[0m         asyncio\u001b[39m.\u001b[39;49mgather(browser\u001b[39m.\u001b[39;49mcreate(\u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs))\n\u001b[1;32m    207\u001b[0m     )[\u001b[39m0\u001b[39m]\n\u001b[1;32m    209\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_user_agent \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_browser\u001b[39m.\u001b[39muser_agent\n\u001b[1;32m    211\u001b[0m \u001b[39mtry\u001b[39;00m:\n",
      "File \u001b[0;32m/usr/lib/python3.8/asyncio/base_events.py:592\u001b[0m, in \u001b[0;36mBaseEventLoop.run_until_complete\u001b[0;34m(self, future)\u001b[0m\n\u001b[1;32m    581\u001b[0m \u001b[39m\u001b[39m\u001b[39m\"\"\"Run until the Future is done.\u001b[39;00m\n\u001b[1;32m    582\u001b[0m \n\u001b[1;32m    583\u001b[0m \u001b[39mIf the argument is a coroutine, it is wrapped in a Task.\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    589\u001b[0m \u001b[39mReturn the Future's result, or raise its exception.\u001b[39;00m\n\u001b[1;32m    590\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[1;32m    591\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_check_closed()\n\u001b[0;32m--> 592\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_check_running()\n\u001b[1;32m    594\u001b[0m new_task \u001b[39m=\u001b[39m \u001b[39mnot\u001b[39;00m futures\u001b[39m.\u001b[39misfuture(future)\n\u001b[1;32m    595\u001b[0m future \u001b[39m=\u001b[39m tasks\u001b[39m.\u001b[39mensure_future(future, loop\u001b[39m=\u001b[39m\u001b[39mself\u001b[39m)\n",
      "File \u001b[0;32m/usr/lib/python3.8/asyncio/base_events.py:552\u001b[0m, in \u001b[0;36mBaseEventLoop._check_running\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    550\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_check_running\u001b[39m(\u001b[39mself\u001b[39m):\n\u001b[1;32m    551\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mis_running():\n\u001b[0;32m--> 552\u001b[0m         \u001b[39mraise\u001b[39;00m \u001b[39mRuntimeError\u001b[39;00m(\u001b[39m'\u001b[39m\u001b[39mThis event loop is already running\u001b[39m\u001b[39m'\u001b[39m)\n\u001b[1;32m    553\u001b[0m     \u001b[39mif\u001b[39;00m events\u001b[39m.\u001b[39m_get_running_loop() \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[1;32m    554\u001b[0m         \u001b[39mraise\u001b[39;00m \u001b[39mRuntimeError\u001b[39;00m(\n\u001b[1;32m    555\u001b[0m             \u001b[39m'\u001b[39m\u001b[39mCannot run the event loop while another loop is running\u001b[39m\u001b[39m'\u001b[39m)\n",
      "\u001b[0;31mRuntimeError\u001b[0m: This event loop is already running"
     ]
    }
   ],
   "source": [
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "env",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.10"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "0f51a9bc14df96e400041251ed11cbd627d667e4e11457ff074f1ccbe8309834"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
